name: openmhealth_schemas
description: A Flutter implementation of the Open mHealth (omh) schemas. Used for formatting health data collected from mobile phones (mHealth).
version: 0.1.4
author: CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/openmhealth_schemas

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0
  uuid: ^2.0.0
  test: ^1.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^3.0.0

